### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_frameworks_mapsv1#13]
@mar-v-in: Please set automatic builds on every commit.

**Comment by bonanza123** [comment]
Try http://ul.to/2tbjb6sl for the time being.
Warning: fully untested, I just let gradle run and uploaded it as there was no build error. Most likely there is also a good reason why marvin didn't release it yet.

**Comment by ale5000-git** [comment]
Thanks for the build.

PS: It still would be nice to have an automatic build on every commit.

**Comment by ale5000-git** [comment]
Closed in favor of this: https://github.com/microg/microg.org/issues/7
