### ISSUE TITLE
Re-license to Apache 2.0

### ISSUE THREAD

**Issue by nu11point3r** [microg/android_frameworks_mapsv1#4]
Following the trend of other microg projects, and given that this project can be used as a library replacement for the proprietary Google Maps in applications, would it be possible to re-license this project as Apache 2.0? This would make inclusion in applications easier license-wise as it could be included in non-GPL'd projects.

From the wording in the license of the [previous version of this project](https://github.com/mar-v-in/MapsAPI/blob/master/README.md), it appeared that this project was only GPL licensed because osmdroid was LGPL licensed at the time. This is [no longer the case](https://code.google.com/p/osmdroid/issues/detail?id=485&can=1&colspec=ID%20Type%20Status%20Priority%20Stars%20Owner%20Summary) as osmdroid is now also [Apache 2.0 licensed](https://github.com/osmdroid/osmdroid/blob/master/LICENSE), so the base license of this project could be safely changed (if there is no other GPL'd code).

**Comment by mar-v-in** [comment]
Agreed and updated license with 8b54cba
