### ISSUE TITLE
Missing release files described in readme

### ISSUE THREAD

**Issue by tomikmar** [microg/android_frameworks_mapsv1#5]
In readme file I found that "Release builds may be found on the release page", but release page is empty. It would be great if the build files were available as well.

**Comment by Lekensteyn** [comment]
There is another project with installable files (from the same author, looks abandoned though): https://github.com/mar-v-in/MapsAPI

**Comment by aphirst** [comment]
Mm, this is somewhat odd. It would be great if this could get cleared up.

**Comment by mar-v-in** [comment]
To clear up things a bit: This repo contains a full rewrite and is not the same as mar-v-in/MapsAPI, although both provide more or less the same functionality.
