### ISSUE TITLE
Map view empty in Öffi, other than Location Markers

### ISSUE THREAD

**Issue by aphirst** [microg/android_frameworks_mapsv1#8]
I see that there's another issue (#7) here about [Öffi](http://offi.schildbach.de/download.html) crashing, which I don't experience. Regardless I thought I should post a new issue regarding my own current problem. It relates to another app which doesn't have a Bug Tracker so I thought I'd document it here and then e-mail him with a link to it - I hope that's OK.

I installed the most recent .zip to my Android device running CM12.1 (so Android 5.1.1), also with microg installed from F-Droid (up to date, AFAIK). Before I did this, the "normal" builds of Öffi in the developer's own F-Droid repo refused to install - afterwards, the install was successful.

There are a few modes in Öffi that can display a map, e.g. the one for showing nearby stations. The map pane is visible along with a location marker (indeed, when in an appropriate route mode, other location markers are also visible, e.g. for your destination too), **but with no map content.** I wondered whether there was a setting or something that I'd forgotten to properly configure but as far as I can see there isn't a settings menu for this Maps "package".

I will have time later in the week to try to get some actual debug output, and once I do, I'll post that in a reply. Also if there's any other information that would be useful, don't hesitate to ask. I'll provide that too once I have the time.

**Comment by aphirst** [comment]
Oh, first clarification, I have actually installed this from the other Github repo by the same author, as this repo does not have release builds as the Readme claims. I had actually "confused" the two projects, though I am (mostly) confident that they are in fact the same project.

https://github.com/mar-v-in/MapsAPI

**Comment by aphirst** [comment]
I'm not sure whether the developer intends himself to post in here, but nonetheless he asked me the following question, which seems apt to post (translated) here:

> Who is it that's actually providing the OSM-Tiles for the MapsV1 implementation?

**Comment by schildbach** [comment]
Your symptom description makes me think there is a problem with the Google server authentication (Maps V1 API key).

**Comment by aphirst** [comment]
@schildbach, potentially related or helpful: I got a crash when "playing" with the map view this morning (specifically, I was zooming in and out), and Öffi spat out a debug log of sorts. I saved it, and have just now extracted it from my device: http://sprunge.us/IKBf

**Comment by mar-v-in** [comment]
@aphirst this is a known problem with the old mar-v-in/MapsAPI implementation with latest Android versions due to changes in SD-card access (tile cache is written to sdcard)
The latest version (this repo) does not suffer from that problem, but has the problem described in #7, once it's fixed there will be a new release.
Long term goal is to redirect Maps API v1 calls to Maps API v2, so we can have all its nice features and focus work on a single, vector-tile-based Maps implementation.

**Comment by mar-v-in** [comment]
As this issue is present in mar-v-in/MapsAPI, but should not be in this repos release, I'll close here.
