### ISSUE TITLE
[Feature Request] Local OSM Map Data

### ISSUE THREAD

**Issue by aphirst** [microg/android_frameworks_mapsv1#9]
Could it ever be within the scope of the project to be able to use local OSM map data, rather than having to use a Tile Server?

**Comment by mar-v-in** [comment]
Tiles are not rendered within this implementation and never will be. Maps API v2 uses vector tiles and renders maps based on "typical offline map data", which would make it possible to use offline map data. 

Thus, once redirection to Maps API v2 is done, this feature will be possible. You can open an issue in microg/android_packages_apps_GmsCore for this feature request.

**Comment by aphirst** [comment]
Thanks for the clarification of the situation, in this and in my other report, @mar-v-in . :smile:
